/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ComplianceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COMPLIANCE_OFFICER_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "ORACLE_ROLE"
      | "REASON_ALLOWED"
      | "REASON_RECIPIENT_FROZEN"
      | "REASON_RECIPIENT_GRANDFATHERED"
      | "REASON_RECIPIENT_UNAUTHORIZED"
      | "REASON_SENDER_FROZEN"
      | "REASON_SENDER_UNAUTHORIZED"
      | "RULESET_VERSION"
      | "batchGetStatus"
      | "batchUpdateStatus"
      | "canReceive"
      | "canSend"
      | "canTransfer"
      | "checkTransfer"
      | "getRoleAdmin"
      | "getStatus"
      | "getStatusAsUint"
      | "grantOracleRole"
      | "grantRole"
      | "hasRole"
      | "investorStatus"
      | "isAccredited"
      | "isWhitelisted"
      | "lastUpdatedBlock"
      | "pause"
      | "paused"
      | "renounceRole"
      | "revokeOracleRole"
      | "revokeRole"
      | "supportsInterface"
      | "totalStatusUpdates"
      | "unpause"
      | "updateStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ComplianceChecked"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "StatusUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COMPLIANCE_OFFICER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ORACLE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REASON_ALLOWED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REASON_RECIPIENT_FROZEN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REASON_RECIPIENT_GRANDFATHERED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REASON_RECIPIENT_UNAUTHORIZED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REASON_SENDER_FROZEN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REASON_SENDER_UNAUTHORIZED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RULESET_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchGetStatus",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchUpdateStatus",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "canReceive",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canSend",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canTransfer",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkTransfer",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStatusAsUint",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantOracleRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "investorStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAccredited",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastUpdatedBlock",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeOracleRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalStatusUpdates",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateStatus",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "COMPLIANCE_OFFICER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ORACLE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REASON_ALLOWED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REASON_RECIPIENT_FROZEN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REASON_RECIPIENT_GRANDFATHERED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REASON_RECIPIENT_UNAUTHORIZED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REASON_SENDER_FROZEN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REASON_SENDER_UNAUTHORIZED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RULESET_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchGetStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchUpdateStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canReceive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canSend", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "canTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStatus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStatusAsUint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantOracleRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "investorStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAccredited",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastUpdatedBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeOracleRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStatusUpdates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateStatus",
    data: BytesLike
  ): Result;
}

export namespace ComplianceCheckedEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    allowed: boolean,
    reason: BytesLike
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    allowed: boolean,
    reason: string
  ];
  export interface OutputObject {
    from: string;
    to: string;
    allowed: boolean;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatusUpdatedEvent {
  export type InputTuple = [
    investor: AddressLike,
    oldStatus: BigNumberish,
    newStatus: BigNumberish,
    updatedBy: AddressLike
  ];
  export type OutputTuple = [
    investor: string,
    oldStatus: bigint,
    newStatus: bigint,
    updatedBy: string
  ];
  export interface OutputObject {
    investor: string;
    oldStatus: bigint;
    newStatus: bigint;
    updatedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ComplianceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ComplianceRegistry;
  waitForDeployment(): Promise<this>;

  interface: ComplianceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COMPLIANCE_OFFICER_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  ORACLE_ROLE: TypedContractMethod<[], [string], "view">;

  REASON_ALLOWED: TypedContractMethod<[], [string], "view">;

  REASON_RECIPIENT_FROZEN: TypedContractMethod<[], [string], "view">;

  REASON_RECIPIENT_GRANDFATHERED: TypedContractMethod<[], [string], "view">;

  REASON_RECIPIENT_UNAUTHORIZED: TypedContractMethod<[], [string], "view">;

  REASON_SENDER_FROZEN: TypedContractMethod<[], [string], "view">;

  REASON_SENDER_UNAUTHORIZED: TypedContractMethod<[], [string], "view">;

  RULESET_VERSION: TypedContractMethod<[], [string], "view">;

  batchGetStatus: TypedContractMethod<
    [investors: AddressLike[]],
    [bigint[]],
    "view"
  >;

  batchUpdateStatus: TypedContractMethod<
    [investors: AddressLike[], statuses: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  canReceive: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  canSend: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  canTransfer: TypedContractMethod<
    [from: AddressLike, to: AddressLike, arg2: BigNumberish],
    [[boolean, string] & { allowed: boolean; reason: string }],
    "view"
  >;

  checkTransfer: TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getStatus: TypedContractMethod<
    [investor: AddressLike],
    [[bigint, bigint] & { status: bigint; updatedBlock: bigint }],
    "view"
  >;

  getStatusAsUint: TypedContractMethod<
    [investor: AddressLike],
    [bigint],
    "view"
  >;

  grantOracleRole: TypedContractMethod<
    [oracle: AddressLike],
    [void],
    "nonpayable"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  investorStatus: TypedContractMethod<
    [investor: AddressLike],
    [bigint],
    "view"
  >;

  isAccredited: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  isWhitelisted: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  lastUpdatedBlock: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeOracleRole: TypedContractMethod<
    [oracle: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalStatusUpdates: TypedContractMethod<[], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateStatus: TypedContractMethod<
    [investor: AddressLike, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COMPLIANCE_OFFICER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ORACLE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REASON_ALLOWED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REASON_RECIPIENT_FROZEN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REASON_RECIPIENT_GRANDFATHERED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REASON_RECIPIENT_UNAUTHORIZED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REASON_SENDER_FROZEN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REASON_SENDER_UNAUTHORIZED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RULESET_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "batchGetStatus"
  ): TypedContractMethod<[investors: AddressLike[]], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "batchUpdateStatus"
  ): TypedContractMethod<
    [investors: AddressLike[], statuses: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "canReceive"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "canSend"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "canTransfer"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, arg2: BigNumberish],
    [[boolean, string] & { allowed: boolean; reason: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkTransfer"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getStatus"
  ): TypedContractMethod<
    [investor: AddressLike],
    [[bigint, bigint] & { status: bigint; updatedBlock: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStatusAsUint"
  ): TypedContractMethod<[investor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantOracleRole"
  ): TypedContractMethod<[oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "investorStatus"
  ): TypedContractMethod<[investor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAccredited"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isWhitelisted"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastUpdatedBlock"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeOracleRole"
  ): TypedContractMethod<[oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalStatusUpdates"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateStatus"
  ): TypedContractMethod<
    [investor: AddressLike, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ComplianceChecked"
  ): TypedContractEvent<
    ComplianceCheckedEvent.InputTuple,
    ComplianceCheckedEvent.OutputTuple,
    ComplianceCheckedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "StatusUpdated"
  ): TypedContractEvent<
    StatusUpdatedEvent.InputTuple,
    StatusUpdatedEvent.OutputTuple,
    StatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "ComplianceChecked(address,address,bool,bytes32)": TypedContractEvent<
      ComplianceCheckedEvent.InputTuple,
      ComplianceCheckedEvent.OutputTuple,
      ComplianceCheckedEvent.OutputObject
    >;
    ComplianceChecked: TypedContractEvent<
      ComplianceCheckedEvent.InputTuple,
      ComplianceCheckedEvent.OutputTuple,
      ComplianceCheckedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "StatusUpdated(address,uint8,uint8,address)": TypedContractEvent<
      StatusUpdatedEvent.InputTuple,
      StatusUpdatedEvent.OutputTuple,
      StatusUpdatedEvent.OutputObject
    >;
    StatusUpdated: TypedContractEvent<
      StatusUpdatedEvent.InputTuple,
      StatusUpdatedEvent.OutputTuple,
      StatusUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
