/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IComplianceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchUpdateStatus"
      | "canTransfer"
      | "getStatus"
      | "investorStatus"
      | "isAccredited"
      | "isWhitelisted"
      | "updateStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ComplianceChecked" | "StatusUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchUpdateStatus",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "canTransfer",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "investorStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAccredited",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStatus",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchUpdateStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStatus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "investorStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAccredited",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStatus",
    data: BytesLike
  ): Result;
}

export namespace ComplianceCheckedEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    allowed: boolean,
    reason: BytesLike
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    allowed: boolean,
    reason: string
  ];
  export interface OutputObject {
    from: string;
    to: string;
    allowed: boolean;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatusUpdatedEvent {
  export type InputTuple = [
    investor: AddressLike,
    oldStatus: BigNumberish,
    newStatus: BigNumberish,
    updatedBy: AddressLike
  ];
  export type OutputTuple = [
    investor: string,
    oldStatus: bigint,
    newStatus: bigint,
    updatedBy: string
  ];
  export interface OutputObject {
    investor: string;
    oldStatus: bigint;
    newStatus: bigint;
    updatedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ICompliance extends BaseContract {
  connect(runner?: ContractRunner | null): ICompliance;
  waitForDeployment(): Promise<this>;

  interface: IComplianceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchUpdateStatus: TypedContractMethod<
    [investors: AddressLike[], statuses: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  canTransfer: TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [[boolean, string] & { allowed: boolean; reason: string }],
    "view"
  >;

  getStatus: TypedContractMethod<
    [investor: AddressLike],
    [[bigint, bigint] & { status: bigint; updatedBlock: bigint }],
    "view"
  >;

  investorStatus: TypedContractMethod<
    [investor: AddressLike],
    [bigint],
    "view"
  >;

  isAccredited: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  isWhitelisted: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  updateStatus: TypedContractMethod<
    [investor: AddressLike, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchUpdateStatus"
  ): TypedContractMethod<
    [investors: AddressLike[], statuses: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "canTransfer"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [[boolean, string] & { allowed: boolean; reason: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStatus"
  ): TypedContractMethod<
    [investor: AddressLike],
    [[bigint, bigint] & { status: bigint; updatedBlock: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "investorStatus"
  ): TypedContractMethod<[investor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAccredited"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isWhitelisted"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "updateStatus"
  ): TypedContractMethod<
    [investor: AddressLike, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ComplianceChecked"
  ): TypedContractEvent<
    ComplianceCheckedEvent.InputTuple,
    ComplianceCheckedEvent.OutputTuple,
    ComplianceCheckedEvent.OutputObject
  >;
  getEvent(
    key: "StatusUpdated"
  ): TypedContractEvent<
    StatusUpdatedEvent.InputTuple,
    StatusUpdatedEvent.OutputTuple,
    StatusUpdatedEvent.OutputObject
  >;

  filters: {
    "ComplianceChecked(address,address,bool,bytes32)": TypedContractEvent<
      ComplianceCheckedEvent.InputTuple,
      ComplianceCheckedEvent.OutputTuple,
      ComplianceCheckedEvent.OutputObject
    >;
    ComplianceChecked: TypedContractEvent<
      ComplianceCheckedEvent.InputTuple,
      ComplianceCheckedEvent.OutputTuple,
      ComplianceCheckedEvent.OutputObject
    >;

    "StatusUpdated(address,uint8,uint8,address)": TypedContractEvent<
      StatusUpdatedEvent.InputTuple,
      StatusUpdatedEvent.OutputTuple,
      StatusUpdatedEvent.OutputObject
    >;
    StatusUpdated: TypedContractEvent<
      StatusUpdatedEvent.InputTuple,
      StatusUpdatedEvent.OutputTuple,
      StatusUpdatedEvent.OutputObject
    >;
  };
}
