/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ICustodianInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attestAssetHolding"
      | "getAssetBalance"
      | "verifyAssetOwnership"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "attestAssetHolding",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetBalance",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAssetOwnership",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "attestAssetHolding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssetBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAssetOwnership",
    data: BytesLike
  ): Result;
}

export interface ICustodian extends BaseContract {
  connect(runner?: ContractRunner | null): ICustodian;
  waitForDeployment(): Promise<this>;

  interface: ICustodianInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attestAssetHolding: TypedContractMethod<
    [assetId: BytesLike],
    [string],
    "nonpayable"
  >;

  getAssetBalance: TypedContractMethod<[assetId: BytesLike], [bigint], "view">;

  verifyAssetOwnership: TypedContractMethod<
    [assetId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attestAssetHolding"
  ): TypedContractMethod<[assetId: BytesLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "getAssetBalance"
  ): TypedContractMethod<[assetId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifyAssetOwnership"
  ): TypedContractMethod<[assetId: BytesLike], [boolean], "view">;

  filters: {};
}
