/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICompliance,
  IComplianceInterface,
} from "../../../src/interfaces/ICompliance";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "allowed",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "reason",
        type: "bytes32",
      },
    ],
    name: "ComplianceChecked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "investor",
        type: "address",
      },
      {
        indexed: false,
        internalType: "enum ICompliance.Status",
        name: "oldStatus",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "enum ICompliance.Status",
        name: "newStatus",
        type: "uint8",
      },
      {
        indexed: true,
        internalType: "address",
        name: "updatedBy",
        type: "address",
      },
    ],
    name: "StatusUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "investors",
        type: "address[]",
      },
      {
        internalType: "enum ICompliance.Status[]",
        name: "statuses",
        type: "uint8[]",
      },
    ],
    name: "batchUpdateStatus",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "canTransfer",
    outputs: [
      {
        internalType: "bool",
        name: "allowed",
        type: "bool",
      },
      {
        internalType: "bytes32",
        name: "reason",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "investor",
        type: "address",
      },
    ],
    name: "getStatus",
    outputs: [
      {
        internalType: "enum ICompliance.Status",
        name: "status",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "updatedBlock",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "investor",
        type: "address",
      },
    ],
    name: "investorStatus",
    outputs: [
      {
        internalType: "enum ICompliance.Status",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isAccredited",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isWhitelisted",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "investor",
        type: "address",
      },
      {
        internalType: "enum ICompliance.Status",
        name: "newStatus",
        type: "uint8",
      },
    ],
    name: "updateStatus",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICompliance__factory {
  static readonly abi = _abi;
  static createInterface(): IComplianceInterface {
    return new Interface(_abi) as IComplianceInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ICompliance {
    return new Contract(address, _abi, runner) as unknown as ICompliance;
  }
}
